# fly.toml app configuration file generated for part13-restless-violet-4512 on 2024-12-16T20:15:48+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part13-restless-violet-4512'
primary_region = 'hkg'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
